Casgem_CodeFirstProject/Controllers/AboutController.cs
using Casgem_CodeFirstProject.DAL.Context;
using Casgem_CodeFirstProject.DAL.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Casgem_CodeFirstProject.Controllers
{
    public class AboutController : Controller
    {

        TravelContext travelContext = new TravelContext();
        
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult PartialScript()
        {
            return PartialView();
        }

        public PartialViewResult PartialAboutMe()
        {
            ViewBag.title1 = travelContext.AboutMes.Select(x => x.Title1).FirstOrDefault();
            ViewBag.description1 = travelContext.AboutMes.Select(x => x.Description1).FirstOrDefault();
            ViewBag.imageUrl1 = travelContext.AboutMes.Select(x => x.ImageUrl1).FirstOrDefault();
            return PartialView();
        }

        public PartialViewResult PartialAboutMe2()
        {
            ViewBag.title2 = travelContext.AboutMes.Select(x => x.Title2).FirstOrDefault();
            ViewBag.description2 = travelContext.AboutMes.Select(x => x.Description2).FirstOrDefault();
            ViewBag.imageUrl2 = travelContext.AboutMes.Select(x => x.ImageUrl2).FirstOrDefault();
            return PartialView();
        }

        
        public PartialViewResult PartialGuide()
        {

            var guideSocialMediaList = travelContext.Guides
           .Include("SocialMedia")
           .ToList();

            return PartialView(guideSocialMediaList);

        }

    }

   
}

Casgem_CodeFirstProject/Controllers/DefaultController.cs
using Casgem_CodeFirstProject.DAL.Context;
using Casgem_CodeFirstProject.DAL.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Casgem_CodeFirstProject.Controllers
{
    public class DefaultController : Controller
    {
        TravelContext travelContext = new TravelContext();
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult PartialHead()
        {
            return PartialView();
        }

        public PartialViewResult PartialNavbar()
        {
            ViewBag.phone = travelContext.FooterContacts.Select(x => x.Phone).FirstOrDefault();

            return PartialView();
        }

        public PartialViewResult PartialNavbarScript()
        {
            return PartialView();
        }

        public PartialViewResult PartialFeature()
        {
            ViewBag.title = travelContext.Abouts.Select(x => x.Title).FirstOrDefault();
            ViewBag.description = travelContext.Abouts.Select(x => x.Description).FirstOrDefault();
            
            return PartialView();
        }

        [HttpGet]
        public PartialViewResult PartialHolidayPlan()
        {
            return PartialView();
        }

        [HttpPost]
        public PartialViewResult PartialHolidayPlan(Booking p)
        {
            travelContext.Bookings.Add(p);
            travelContext.SaveChanges();            
            return PartialView();
        }

        public PartialViewResult PartialPlace()
        {
            var values = travelContext.Places.ToList();

            return PartialView(values);
        }

        public PartialViewResult PartialDestination()
        {
            var values = travelContext.Destinations.ToList();
            return PartialView(values);
        }


        public PartialViewResult PartialExplore()
        {
            ViewBag.title = travelContext.Explores.Select(x => x.Title).FirstOrDefault();
            ViewBag.description = travelContext.Explores.Select(x => x.Description).FirstOrDefault();
            ViewBag.imageUrl = travelContext.Explores.Select(x => x.ImageUrl).FirstOrDefault();
            return PartialView();
        }

        public PartialViewResult PartialBookTravel()
        {
            return PartialView();
        }

        public PartialViewResult PartialFooter()
        {
            ViewBag.address = travelContext.FooterContacts.Select(x => x.Address).FirstOrDefault();
            ViewBag.phone = travelContext.FooterContacts.Select(x => x.Phone).FirstOrDefault(); 
            ViewBag.mail = travelContext.FooterContacts.Select(x => x.Mail).FirstOrDefault();
            return PartialView();
        }

        public PartialViewResult PartialSocialMedia()
        {
            var values = travelContext.ContactSocials.ToList();
            return PartialView(values);
        }

        public PartialViewResult PartialCategory()
        {
            var values = travelContext.Categories.ToList();
            return PartialView(values);
        }

        public PartialViewResult PartialGalery()
        {
            var values = travelContext.FooterGaleries.ToList();
            return PartialView(values);
        }

        public PartialViewResult PartialTravelTrip()
        {
            var values = travelContext.FooterTravelTrips.ToList();
            return PartialView(values);
        }

        public PartialViewResult PartialScript()
        {
            return PartialView();
        }
    }
}

Casgem_CodeFirstProject/Controllers/ExploreController.cs
using Casgem_CodeFirstProject.DAL.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Casgem_CodeFirstProject.Controllers
{
    public class ExploreController : Controller
    {
        TravelContext travelContext = new TravelContext();
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult PartialService()
        {
            var values = travelContext.Services.ToList();
            return PartialView(values);
        }

        public PartialViewResult PartialImage()
        {
            var values = travelContext.Galeries.ToList();
            return PartialView(values);
        }
    }
}

Casgem_CodeFirstProject/Views/Explore/Index.cshtml
@{
    Layout = null;
}



<!--
   Author: W3layouts
   Author URL: http://w3layouts.com
-->
<!doctype html>
<html lang="en">
@Html.Action("PartialHead", "Default")
<body id="home">
    @Html.Action("PartialNavbar", "Default")
    @Html.Action("PartialScript", "About")
    <section class="w3l-inner-banner-main">
        <div class="about-inner services editContent">
            <div class="container">

                <div class="breadcrumbs-sub">
                    <ul class="breadcrumbs-custom-path">
                        <li class="right-side propClone"><a href="/Default/Index" class="editContent">Anasayfa <span class="fa fa-angle-right" aria-hidden="true"></span></a> <p></li>
                        <li class="active editContent">Keşfet</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumbs //-->
    @Html.Action("PartialService")

    @Html.Action("PartialImage")

    <section class="w3l-footer-29-main">
        <div class="footer-29 py-5 ">
            <div class="container">
                <div class="grid-col-4 footer-top-29">
                    <div class="footer-list-29 footer-1">
                        @Html.Action("PartialFooter", "Default")
                        @Html.Action("PartialSocialMedia", "Default")
                    </div>

                    @Html.Action("PartialCategory", "Default")


                    @Html.Action("PartialGalery", "Default")

                    @Html.Action("PartialTravelTrip", "Default")


                </div>
                <div class=" bottom-copies text-center">
                    <p class="copy-footer-29">© 2020 Go Trip. All rights reserved | Designed by <a href="//w3layouts.com">W3layouts</a></p>
                </div>
            </div>
        </div>
    </section>

    <!-- move top -->
    @Html.Action("PartialScript", "Default")

</body>

</html>

Casgem_CodeFirstProject/Views/Explore/PartialImage.cshtml
@model List<Casgem_CodeFirstProject.DAL.Entities.Galery>
<section class="w3l-services-two" id="services">
    <div class="service-single-page editContent">
        <div class="container">
            <div class="gallery-image row">

                @foreach (var item in Model)
                {
                    <div class="img-box col-lg-4 col-md-6">
                        <img src="@item.ImageUrl" alt="product" class="img-responsive ">
                        <h5 class="mt-2"><a href="#">@item.Title</a></h5>
                        <p class="para">@item.Description</p>
                    </div>
                }


            </div>
        </div>
    </div>
</section>

Casgem_CodeFirstProject/Views/Explore/PartialService.cshtml
@model List<Casgem_CodeFirstProject.DAL.Entities.Service>

<section class="w3l-recent-work-hobbies" id="services">
    <div class="recent-work editContent">
        <div class="container">
            <div class="row service-service">
                @foreach (var item in Model)
                {
                    <div class="col-lg-4 col-md-6 propClone about-line-top ">
                        <div class="color-white editContent">
                            <div class="icon-back"><span class="@item.Icon"></span></div>

                            <h5>
                                <a href="#" class="editContent">
                                    @item.Title
                                </a>
                            </h5>
                            <p class="para editContent">
                                @item.Description
                            </p>
                        </div>
                    </div>
                }


            </div>
        </div>
    </div>
</section>